Enable nncf for multihead classification
openvinotoolkit/deep-object-reid pull request #226
Opened 2022-07-28 06:21 UTC by sooahleex

Apply nncf to multihead classification in the evaluation of the model.

2022-07-28 11:45 UTC, sovrasov commented
@sooahleex overall the changes look fine to me, but experiments and tests are required. The tests could be added [here](https://github.com/openvinotoolkit/training_extensions/blob/develop/external/model-preparation-algorithm/tests/test_ote_training.py), but honestly I'm a bit confused by the fact that the NNCF task is still located in deep-object-reid. Shouldn't it be moved to the MPA subfolder?

2022-07-28 23:46 UTC, goodsong81 commented
> @sooahleex overall the changes look fine to me, but experiments and tests are required. The tests could be added [here](https://github.com/openvinotoolkit/training_extensions/blob/develop/external/model-preparation-algorithm/tests/test_ote_training.py), but honestly I'm a bit confused by the fact that the NNCF task is still located in deep-object-reid. Shouldn't it be moved to the MPA subfolder?

Currently, we have not yet enabled NNCF support for mmcls so that we delegate NNCF optimization for classification tasks to deep-object-reid. (We guarantee checkpoint compatibility for that).
In my opinion, OTE side test is enough for this purpose.
@sooahleex Could you add links to OTE or SC test build that you tested NNCF functionality?

2022-07-29 01:05 UTC, JihwanEom requested changes

2022-07-29 01:05 UTC, JihwanEom commented on torchreid/engine/builder.py
> +NNCF_ENABLED_LOSS = ['softmax', 'am_softmax', 'am_binary']
For multihead classification, loss_name comes as `softmax,asl` , so asl will raise error I think. Could you revise this line to include `asl`?

2022-07-29 01:07 UTC, JihwanEom commented
> @JihwanEom Could you spot the test for this change? Maybe we have API/CLI tests for this.

Yes, I'll test for this PR

2022-07-29 01:27 UTC, JihwanEom commented on torchreid/engine/builder.py
> +        if not any(loss_name in NNCF_ENABLED_LOSS for loss_name in cfg.loss.name.split(',')):
Could you change from `any` to `all`? I think if not enabled loss comes, this if statement should raise error.

2022-08-01 15:10 UTC, sooahleex commented
> Currently, we have not yet enabled NNCF support for mmcls so that we delegate NNCF optimization for classification tasks to deep-object-reid. (We guarantee checkpoint compatibility for that). In my opinion, OTE side test is enough for this purpose. @sooahleex Could you add links to OTE or SC test build that you tested NNCF functionality? @JihwanEom Could you spot the test for this change? Maybe we have API/CLI tests for this.

This is the [link](http://validationreports.sclab.intel.com:8004/reports/build_number_report?test_session_build_number=IMPTOps-35498&environment=mclx02) of the SC test build. All the tests are passed well, and when I tested this in UI, it worked out.

2022-08-01 16:27 UTC, sovrasov commented
SC build doesn't test NNCF unfortunately, so now we know that this PR at least doesn't break anything and we have to rely on manual testing only.

2022-08-12 07:37 UTC, JihwanEom commented
Hi all, NNCF test for multihead classification was conducted on this OTE PR: https://github.com/openvinotoolkit/training_extensions/pull/1192
I could check all the NNCF test cases are passed. If there is some performance issue, we will create another ticket.

2022-08-12 07:37 UTC, JihwanEom approved these changes
LGTM

2022-08-12 07:38 UTC, merged