Handle mmxxx checkpoint on NNCF for resume
openvinotoolkit/deep-object-reid pull request #233
Opened 2022-09-01 06:22 UTC by JihwanEom

## This PR includes:
### Summary:
- Handle mmxxx checkpoint on NNCF to support resume in OTE
- Related OTE PR: https://github.com/openvinotoolkit/training_extensions/pull/1234

2022-09-01 08:39 UTC, jaegukhyun approved these changes
LGTM

2022-09-02 08:38 UTC, sovrasov requested changes
@JihwanEom please retarget this PR to release/OTE_0.3.0 branch, since the corresponding PR to OTE also targets OTE release branch.

2022-09-02 08:39 UTC, JihwanEom commented
> @JihwanEom please retarget this PR to release/OTE_0.3.0 branch, since the corresponding PR to OTE also targets OTE release branch.

Reflected, thank you!

2022-09-02 08:42 UTC, sovrasov approved these changes

2022-09-02 08:42 UTC, merged